modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/ThermalExtra/issues"

[[mods]]
modId = "thermal_more"
version = "3.0.9-1.20.1"
displayName = "Thermal More"
displayURL = "example.org"
#logoFile="tinkers_reforged_logo.png"
credits = "Team CoFH, Mrthomas20121"
authors = "Elephant_dev"
description = '''
Adds more integral components to Thermal
'''

[[dependencies.thermal_more]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"